runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
  VISION_API: xxxxxxx
  API_KEY: xxxxxxxxxx
  AUTH_DOMAIN: xxxxxx
  DATABASE_URL: xxxxx
  STORAGE_BUCKET: xxx
